runtime: python39
instance_class: F1
entrypoint: |
  chmod +x entrypoint.sh
  ./entrypoint.sh

runtime_config:
  operating_system: ubuntu22

service_account: petdoc-capstone-project@appspot.gserviceaccount.com

vpc_access_connector:
  name: projects/petdoc-capstone-project/locations/asia-southeast2/connectors/cloudrun-connector

beta_settings:
  cloud_sql_instances: INSTANCE_CONNECTION_NAME=tcp:5432

env_variables:
  VERSION: v1
  JWT_ACCESS_TOKEN_SECRET: AHBiadbiaeud92uedb9ub9wue92
  JWT_REFRESH_TOKEN_SECRET: eu92uidbsAHBiadbiauedb9ub9wue92eu
  JWT_ALGORITHM: HS512
  JWT_ACCESS_TOKEN_EXPIRE: 1
  JWT_REFRESH_TOKEN_EXPIRE: 7
  POSTGRES_HOST: "127.0.0.1"
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASS: admin
  POSTGRES_DB: coba_capstone

automatic_scaling:
  target_cpu_utilization: 0.90
  min_instances: 1
  max_instances: 3
  min_pending_latency: 800ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
    