"""migrate

Revision ID: 1f1c1445ebf8
Revises: 2150a1fde263
Create Date: 2023-08-24 19:41:57.302100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1c1445ebf8'
down_revision: Union[str, None] = '2150a1fde263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('owner_id', sa.String(), nullable=True))
    op.drop_constraint('credentials_user_id_fkey', 'credentials', type_='foreignkey')
    op.create_foreign_key(None, 'credentials', 'users', ['owner_id'], ['id'])
    op.drop_column('credentials', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.create_foreign_key('credentials_user_id_fkey', 'credentials', 'users', ['user_id'], ['id'])
    op.drop_column('credentials', 'owner_id')
    # ### end Alembic commands ###
