"""migrate

Revision ID: 7c5da9ade4eb
Revises: 1f1c1445ebf8
Create Date: 2023-08-26 16:06:44.409212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5da9ade4eb'
down_revision: Union[str, None] = '1f1c1445ebf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'credentials', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credentials', type_='unique')
    # ### end Alembic commands ###
