"""migrate

Revision ID: c28839b4cec6
Revises: 95abf8ca240e
Create Date: 2023-08-23 17:49:50.008813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28839b4cec6'
down_revision: Union[str, None] = '95abf8ca240e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createdAt', sa.Date(), nullable=True))
    op.drop_column('users', 'createAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createAt', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('users', 'createdAt')
    # ### end Alembic commands ###
