"""migrate postgres

Revision ID: e14619195f71
Revises: 7ca039761350
Create Date: 2023-08-23 14:30:43.021537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14619195f71'
down_revision: Union[str, None] = '7ca039761350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(length=16), nullable=True),
    sa.Column('fullname', sa.String(length=32), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('createAt', sa.Date(), nullable=True),
    sa.Column('updatedAt', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_email'), 'credentials', ['email'], unique=True)
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_email'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
